[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
escrow = "AdSqjLd5Zw8cSm7F1nGuLWJVbMZj79fBoPuX5hWCwaGa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
